/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9 */

#ifndef PB_AGENTX_IPC_V1_AGENTX_IPC_PB_H_INCLUDED
#define PB_AGENTX_IPC_V1_AGENTX_IPC_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _agentx_ipc_v1_ValueType {
    agentx_ipc_v1_ValueType_VALUE_TYPE_UNSPECIFIED = 0,
    agentx_ipc_v1_ValueType_VALUE_TYPE_INT32 = 1,
    agentx_ipc_v1_ValueType_VALUE_TYPE_UINT32 = 2,
    agentx_ipc_v1_ValueType_VALUE_TYPE_UINT64 = 3,
    agentx_ipc_v1_ValueType_VALUE_TYPE_BYTES = 4
} agentx_ipc_v1_ValueType;

typedef enum _agentx_ipc_v1_Status {
    agentx_ipc_v1_Status_STATUS_UNSPECIFIED = 0,
    agentx_ipc_v1_Status_STATUS_OK = 1,
    agentx_ipc_v1_Status_STATUS_NOT_FOUND = 2,
    agentx_ipc_v1_Status_STATUS_TYPE_MISMATCH = 3,
    agentx_ipc_v1_Status_STATUS_INVALID = 4, /* unknown key, malformed request, bad value */
    agentx_ipc_v1_Status_STATUS_READ_ONLY = 5, /* key is not writable through this path */
    agentx_ipc_v1_Status_STATUS_STORAGE_ERROR = 6 /* LMDB / OS level failure */
} agentx_ipc_v1_Status;

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(256) agentx_ipc_v1_Value_bytes_val_t;
typedef struct _agentx_ipc_v1_Value {
    agentx_ipc_v1_ValueType type;
    int32_t int32_val;
    uint32_t uint32_val;
    uint64_t uint64_val;
    agentx_ipc_v1_Value_bytes_val_t bytes_val;
} agentx_ipc_v1_Value;

/* Ask the subagent to write a configuration object it owns. */
typedef struct _agentx_ipc_v1_WriteConfigRequest {
    char key[64]; /* MIB object name, e.g. "sampleIntervalSec" */
    bool has_value;
    agentx_ipc_v1_Value value;
} agentx_ipc_v1_WriteConfigRequest;

typedef struct _agentx_ipc_v1_WriteConfigResponse {
    agentx_ipc_v1_Status status;
    char message[128]; /* human readable detail, empty on success */
} agentx_ipc_v1_WriteConfigResponse;

/* Read back a configuration object (convenience; the app may also open
 config.lmdb read-only). */
typedef struct _agentx_ipc_v1_ReadConfigRequest {
    char key[64];
} agentx_ipc_v1_ReadConfigRequest;

typedef struct _agentx_ipc_v1_ReadConfigResponse {
    agentx_ipc_v1_Status status;
    bool has_value;
    agentx_ipc_v1_Value value;
    char message[128];
} agentx_ipc_v1_ReadConfigResponse;

/* Ask the subagent to emit demoTempAlarm on the application's behalf. */
typedef struct _agentx_ipc_v1_SendTrapRequest {
    char trap_name[64]; /* e.g. "demoTempAlarm" */
} agentx_ipc_v1_SendTrapRequest;

typedef struct _agentx_ipc_v1_SendTrapResponse {
    agentx_ipc_v1_Status status;
    char message[128];
} agentx_ipc_v1_SendTrapResponse;

typedef struct _agentx_ipc_v1_PingRequest {
    uint32_t nonce;
} agentx_ipc_v1_PingRequest;

typedef struct _agentx_ipc_v1_PingResponse {
    uint32_t nonce;
} agentx_ipc_v1_PingResponse;

typedef struct _agentx_ipc_v1_Envelope {
    uint32_t request_id; /* echoed back by the server; 0 means "don't care" */
    pb_size_t which_body;
    union {
        agentx_ipc_v1_WriteConfigRequest write_config_request;
        agentx_ipc_v1_WriteConfigResponse write_config_response;
        agentx_ipc_v1_ReadConfigRequest read_config_request;
        agentx_ipc_v1_ReadConfigResponse read_config_response;
        agentx_ipc_v1_SendTrapRequest send_trap_request;
        agentx_ipc_v1_SendTrapResponse send_trap_response;
        agentx_ipc_v1_PingRequest ping_request;
        agentx_ipc_v1_PingResponse ping_response;
    } body;
} agentx_ipc_v1_Envelope;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _agentx_ipc_v1_ValueType_MIN agentx_ipc_v1_ValueType_VALUE_TYPE_UNSPECIFIED
#define _agentx_ipc_v1_ValueType_MAX agentx_ipc_v1_ValueType_VALUE_TYPE_BYTES
#define _agentx_ipc_v1_ValueType_ARRAYSIZE ((agentx_ipc_v1_ValueType)(agentx_ipc_v1_ValueType_VALUE_TYPE_BYTES+1))

#define _agentx_ipc_v1_Status_MIN agentx_ipc_v1_Status_STATUS_UNSPECIFIED
#define _agentx_ipc_v1_Status_MAX agentx_ipc_v1_Status_STATUS_STORAGE_ERROR
#define _agentx_ipc_v1_Status_ARRAYSIZE ((agentx_ipc_v1_Status)(agentx_ipc_v1_Status_STATUS_STORAGE_ERROR+1))

#define agentx_ipc_v1_Value_type_ENUMTYPE agentx_ipc_v1_ValueType


#define agentx_ipc_v1_WriteConfigResponse_status_ENUMTYPE agentx_ipc_v1_Status


#define agentx_ipc_v1_ReadConfigResponse_status_ENUMTYPE agentx_ipc_v1_Status


#define agentx_ipc_v1_SendTrapResponse_status_ENUMTYPE agentx_ipc_v1_Status





/* Initializer values for message structs */
#define agentx_ipc_v1_Value_init_default         {_agentx_ipc_v1_ValueType_MIN, 0, 0, 0, {0, {0}}}
#define agentx_ipc_v1_WriteConfigRequest_init_default {"", false, agentx_ipc_v1_Value_init_default}
#define agentx_ipc_v1_WriteConfigResponse_init_default {_agentx_ipc_v1_Status_MIN, ""}
#define agentx_ipc_v1_ReadConfigRequest_init_default {""}
#define agentx_ipc_v1_ReadConfigResponse_init_default {_agentx_ipc_v1_Status_MIN, false, agentx_ipc_v1_Value_init_default, ""}
#define agentx_ipc_v1_SendTrapRequest_init_default {""}
#define agentx_ipc_v1_SendTrapResponse_init_default {_agentx_ipc_v1_Status_MIN, ""}
#define agentx_ipc_v1_PingRequest_init_default   {0}
#define agentx_ipc_v1_PingResponse_init_default  {0}
#define agentx_ipc_v1_Envelope_init_default      {0, 0, {agentx_ipc_v1_WriteConfigRequest_init_default}}
#define agentx_ipc_v1_Value_init_zero            {_agentx_ipc_v1_ValueType_MIN, 0, 0, 0, {0, {0}}}
#define agentx_ipc_v1_WriteConfigRequest_init_zero {"", false, agentx_ipc_v1_Value_init_zero}
#define agentx_ipc_v1_WriteConfigResponse_init_zero {_agentx_ipc_v1_Status_MIN, ""}
#define agentx_ipc_v1_ReadConfigRequest_init_zero {""}
#define agentx_ipc_v1_ReadConfigResponse_init_zero {_agentx_ipc_v1_Status_MIN, false, agentx_ipc_v1_Value_init_zero, ""}
#define agentx_ipc_v1_SendTrapRequest_init_zero  {""}
#define agentx_ipc_v1_SendTrapResponse_init_zero {_agentx_ipc_v1_Status_MIN, ""}
#define agentx_ipc_v1_PingRequest_init_zero      {0}
#define agentx_ipc_v1_PingResponse_init_zero     {0}
#define agentx_ipc_v1_Envelope_init_zero         {0, 0, {agentx_ipc_v1_WriteConfigRequest_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define agentx_ipc_v1_Value_type_tag             1
#define agentx_ipc_v1_Value_int32_val_tag        2
#define agentx_ipc_v1_Value_uint32_val_tag       3
#define agentx_ipc_v1_Value_uint64_val_tag       4
#define agentx_ipc_v1_Value_bytes_val_tag        5
#define agentx_ipc_v1_WriteConfigRequest_key_tag 1
#define agentx_ipc_v1_WriteConfigRequest_value_tag 2
#define agentx_ipc_v1_WriteConfigResponse_status_tag 1
#define agentx_ipc_v1_WriteConfigResponse_message_tag 2
#define agentx_ipc_v1_ReadConfigRequest_key_tag  1
#define agentx_ipc_v1_ReadConfigResponse_status_tag 1
#define agentx_ipc_v1_ReadConfigResponse_value_tag 2
#define agentx_ipc_v1_ReadConfigResponse_message_tag 3
#define agentx_ipc_v1_SendTrapRequest_trap_name_tag 1
#define agentx_ipc_v1_SendTrapResponse_status_tag 1
#define agentx_ipc_v1_SendTrapResponse_message_tag 2
#define agentx_ipc_v1_PingRequest_nonce_tag      1
#define agentx_ipc_v1_PingResponse_nonce_tag     1
#define agentx_ipc_v1_Envelope_request_id_tag    1
#define agentx_ipc_v1_Envelope_write_config_request_tag 10
#define agentx_ipc_v1_Envelope_write_config_response_tag 11
#define agentx_ipc_v1_Envelope_read_config_request_tag 12
#define agentx_ipc_v1_Envelope_read_config_response_tag 13
#define agentx_ipc_v1_Envelope_send_trap_request_tag 14
#define agentx_ipc_v1_Envelope_send_trap_response_tag 15
#define agentx_ipc_v1_Envelope_ping_request_tag  16
#define agentx_ipc_v1_Envelope_ping_response_tag 17

/* Struct field encoding specification for nanopb */
#define agentx_ipc_v1_Value_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1) \
X(a, STATIC,   SINGULAR, INT32,    int32_val,         2) \
X(a, STATIC,   SINGULAR, UINT32,   uint32_val,        3) \
X(a, STATIC,   SINGULAR, UINT64,   uint64_val,        4) \
X(a, STATIC,   SINGULAR, BYTES,    bytes_val,         5)
#define agentx_ipc_v1_Value_CALLBACK NULL
#define agentx_ipc_v1_Value_DEFAULT NULL

#define agentx_ipc_v1_WriteConfigRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   key,               1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  value,             2)
#define agentx_ipc_v1_WriteConfigRequest_CALLBACK NULL
#define agentx_ipc_v1_WriteConfigRequest_DEFAULT NULL
#define agentx_ipc_v1_WriteConfigRequest_value_MSGTYPE agentx_ipc_v1_Value

#define agentx_ipc_v1_WriteConfigResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    status,            1) \
X(a, STATIC,   SINGULAR, STRING,   message,           2)
#define agentx_ipc_v1_WriteConfigResponse_CALLBACK NULL
#define agentx_ipc_v1_WriteConfigResponse_DEFAULT NULL

#define agentx_ipc_v1_ReadConfigRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   key,               1)
#define agentx_ipc_v1_ReadConfigRequest_CALLBACK NULL
#define agentx_ipc_v1_ReadConfigRequest_DEFAULT NULL

#define agentx_ipc_v1_ReadConfigResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    status,            1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  value,             2) \
X(a, STATIC,   SINGULAR, STRING,   message,           3)
#define agentx_ipc_v1_ReadConfigResponse_CALLBACK NULL
#define agentx_ipc_v1_ReadConfigResponse_DEFAULT NULL
#define agentx_ipc_v1_ReadConfigResponse_value_MSGTYPE agentx_ipc_v1_Value

#define agentx_ipc_v1_SendTrapRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   trap_name,         1)
#define agentx_ipc_v1_SendTrapRequest_CALLBACK NULL
#define agentx_ipc_v1_SendTrapRequest_DEFAULT NULL

#define agentx_ipc_v1_SendTrapResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    status,            1) \
X(a, STATIC,   SINGULAR, STRING,   message,           2)
#define agentx_ipc_v1_SendTrapResponse_CALLBACK NULL
#define agentx_ipc_v1_SendTrapResponse_DEFAULT NULL

#define agentx_ipc_v1_PingRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   nonce,             1)
#define agentx_ipc_v1_PingRequest_CALLBACK NULL
#define agentx_ipc_v1_PingRequest_DEFAULT NULL

#define agentx_ipc_v1_PingResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   nonce,             1)
#define agentx_ipc_v1_PingResponse_CALLBACK NULL
#define agentx_ipc_v1_PingResponse_DEFAULT NULL

#define agentx_ipc_v1_Envelope_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   request_id,        1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,write_config_request,body.write_config_request),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,write_config_response,body.write_config_response),  11) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,read_config_request,body.read_config_request),  12) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,read_config_response,body.read_config_response),  13) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,send_trap_request,body.send_trap_request),  14) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,send_trap_response,body.send_trap_response),  15) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,ping_request,body.ping_request),  16) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,ping_response,body.ping_response),  17)
#define agentx_ipc_v1_Envelope_CALLBACK NULL
#define agentx_ipc_v1_Envelope_DEFAULT NULL
#define agentx_ipc_v1_Envelope_body_write_config_request_MSGTYPE agentx_ipc_v1_WriteConfigRequest
#define agentx_ipc_v1_Envelope_body_write_config_response_MSGTYPE agentx_ipc_v1_WriteConfigResponse
#define agentx_ipc_v1_Envelope_body_read_config_request_MSGTYPE agentx_ipc_v1_ReadConfigRequest
#define agentx_ipc_v1_Envelope_body_read_config_response_MSGTYPE agentx_ipc_v1_ReadConfigResponse
#define agentx_ipc_v1_Envelope_body_send_trap_request_MSGTYPE agentx_ipc_v1_SendTrapRequest
#define agentx_ipc_v1_Envelope_body_send_trap_response_MSGTYPE agentx_ipc_v1_SendTrapResponse
#define agentx_ipc_v1_Envelope_body_ping_request_MSGTYPE agentx_ipc_v1_PingRequest
#define agentx_ipc_v1_Envelope_body_ping_response_MSGTYPE agentx_ipc_v1_PingResponse

extern const pb_msgdesc_t agentx_ipc_v1_Value_msg;
extern const pb_msgdesc_t agentx_ipc_v1_WriteConfigRequest_msg;
extern const pb_msgdesc_t agentx_ipc_v1_WriteConfigResponse_msg;
extern const pb_msgdesc_t agentx_ipc_v1_ReadConfigRequest_msg;
extern const pb_msgdesc_t agentx_ipc_v1_ReadConfigResponse_msg;
extern const pb_msgdesc_t agentx_ipc_v1_SendTrapRequest_msg;
extern const pb_msgdesc_t agentx_ipc_v1_SendTrapResponse_msg;
extern const pb_msgdesc_t agentx_ipc_v1_PingRequest_msg;
extern const pb_msgdesc_t agentx_ipc_v1_PingResponse_msg;
extern const pb_msgdesc_t agentx_ipc_v1_Envelope_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define agentx_ipc_v1_Value_fields &agentx_ipc_v1_Value_msg
#define agentx_ipc_v1_WriteConfigRequest_fields &agentx_ipc_v1_WriteConfigRequest_msg
#define agentx_ipc_v1_WriteConfigResponse_fields &agentx_ipc_v1_WriteConfigResponse_msg
#define agentx_ipc_v1_ReadConfigRequest_fields &agentx_ipc_v1_ReadConfigRequest_msg
#define agentx_ipc_v1_ReadConfigResponse_fields &agentx_ipc_v1_ReadConfigResponse_msg
#define agentx_ipc_v1_SendTrapRequest_fields &agentx_ipc_v1_SendTrapRequest_msg
#define agentx_ipc_v1_SendTrapResponse_fields &agentx_ipc_v1_SendTrapResponse_msg
#define agentx_ipc_v1_PingRequest_fields &agentx_ipc_v1_PingRequest_msg
#define agentx_ipc_v1_PingResponse_fields &agentx_ipc_v1_PingResponse_msg
#define agentx_ipc_v1_Envelope_fields &agentx_ipc_v1_Envelope_msg

/* Maximum encoded size of messages (where known) */
#define AGENTX_IPC_V1_AGENTX_IPC_PB_H_MAX_SIZE   agentx_ipc_v1_Envelope_size
#define agentx_ipc_v1_Envelope_size              433
#define agentx_ipc_v1_PingRequest_size           6
#define agentx_ipc_v1_PingResponse_size          6
#define agentx_ipc_v1_ReadConfigRequest_size     65
#define agentx_ipc_v1_ReadConfigResponse_size    424
#define agentx_ipc_v1_SendTrapRequest_size       65
#define agentx_ipc_v1_SendTrapResponse_size      132
#define agentx_ipc_v1_Value_size                 289
#define agentx_ipc_v1_WriteConfigRequest_size    357
#define agentx_ipc_v1_WriteConfigResponse_size   132

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
