/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9 */

#include "agentx_ipc.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(agentx_ipc_v1_Value, agentx_ipc_v1_Value, 2)


PB_BIND(agentx_ipc_v1_WriteConfigRequest, agentx_ipc_v1_WriteConfigRequest, 2)


PB_BIND(agentx_ipc_v1_WriteConfigResponse, agentx_ipc_v1_WriteConfigResponse, AUTO)


PB_BIND(agentx_ipc_v1_ReadConfigRequest, agentx_ipc_v1_ReadConfigRequest, AUTO)


PB_BIND(agentx_ipc_v1_ReadConfigResponse, agentx_ipc_v1_ReadConfigResponse, 2)


PB_BIND(agentx_ipc_v1_SendTrapRequest, agentx_ipc_v1_SendTrapRequest, AUTO)


PB_BIND(agentx_ipc_v1_SendTrapResponse, agentx_ipc_v1_SendTrapResponse, AUTO)


PB_BIND(agentx_ipc_v1_PingRequest, agentx_ipc_v1_PingRequest, AUTO)


PB_BIND(agentx_ipc_v1_PingResponse, agentx_ipc_v1_PingResponse, AUTO)


PB_BIND(agentx_ipc_v1_Envelope, agentx_ipc_v1_Envelope, 2)







